import type { Product } from '../../../domain/product/product.type'

export const products: Product[] = [
  // LIMPIEZA
  {
    id: '1', 
    name: 'Low pH Good Morning Gel Cleanser', 
    brand: 'COSRX', 
    category: 'Limpieza', 
    price: 145.00, 
    image: 'images/Low-pH-Good-Morning-Gel-Cleanser.png',
    stock: 20, 
    skinType: 'Grasa',
  },
  {
    id: '2', 
    name: 'Centella Cleansing Foam', 
    brand: 'Mixsoon', 
    category: 'Limpieza', 
    price: 170.00, 
    image: 'images/Centella-Cleansing-Foam.png', 
    stock: 16, 
    skinType: 'Mixta',
  },
  {
    id: '3',
    name: 'Rice Water Cleanser',
    brand: 'Beauty of Joseon',
    category: 'Limpieza',
    price: 180.00,
    image: 'images/Rice-Water-Cleanser.png',
    stock: 14, skinType: 'Seca',
  },
  {
    id: '4',
    name: 'Defense Barrier Cleanser',
    brand: 'Purito',
    category: 'Limpieza',
    price: 195.00,
    image: 'images/Defense-Barrier-Cleanser.png',
    stock: 12,
    skinType: 'Sensible',
  },
  {
    id: '5',
    name: 'Madagascar Centella Ampoule Foam',
    brand: 'Skin1004',
    category: 'Limpieza',
    price: 185.00,
    image: 'images/Madagascar-Centella-Ampoule-Foam.png',
    stock: 18,
    skinType: 'Grasa',
  },
  {
    id: '6',
    name: 'Snail Mucin Cleanser',
    brand: 'COSRX',
    category: 'Limpieza',
    price: 175.00,
    image: 'images/Snail-Mucin-Cleanser.png',
    stock: 15,
    skinType: 'Mixta',
  },

  // TÓNICOS
  {
    id: '7',
    name: 'Hydrium Watery Toner',
    brand: 'COSRX',
    category: 'Tónicos',
    price: 185.00,
    image: 'images/Hydrium-Watery-Toner.png',
    stock: 12,
    skinType: 'Mixta',
  },
  {
    id: '8',
    name: 'Galactomyces Toner',
    brand: 'Mixsoon',
    category: 'Tónicos',
    price: 220.00,
    image: 'images/Galactomyces-Toner.png',
    stock: 13,
    skinType: 'Seca',
  },
  {
    id: '9',
    name: 'Ginseng Essence Water',
    brand: 'Beauty of Joseon',
    category: 'Tónicos',
    price: 215.00,
    image: 'images/Ginseng-Essence-Water.png',
    stock: 17,
    skinType: 'Seca',
  },
  {
    id: '10',
    name: 'Centella Unscented Toner',
    brand: 'Purito',
    category: 'Tónicos',
    price: 210.00,
    image: 'images/Centella-Unscented-Toner.png',
    stock: 10,
    skinType: 'Sensible',
  },
  {
    id: '11',
    name: 'Madagascar Centella Tone Brightening Toner',
    brand: 'Skin1004',
    category: 'Tónicos',
    price: 225.00,
    image: 'images/Madagascar-Centella-Tone-Brightening-Toner.png',
    stock: 13,
    skinType: 'Mixta',
  },
  {
    id: '12',
    name: 'Propolis Synergy Toner',
    brand: 'COSRX',
    category: 'Tónicos',
    price: 230.00,
    image: 'images/Propolis-Synergy-Toner.png',
    stock: 11,
    skinType: 'Grasa',
  },

  // SÉRUMS
  {
    id: '13',
    name: 'Advanced Snail 96 Mucin Essence',
    brand: 'COSRX',
    category: 'Sérums',
    price: 210.00,
    image: 'images/Advanced-Snail-96-Mucin-Essence.png',
    stock: 18,
    skinType: 'Seca',
  },
  {
    id: '14',
    name: 'Bean Essence',
    brand: 'Mixsoon',
    category: 'Sérums',
    price: 260.00,
    image: 'images/Bean-Essence.png',
    stock: 11,
    skinType: 'Mixta',
  },
  {
    id: '15',
    name: 'Glow Deep Serum',
    brand: 'Beauty of Joseon',
    category: 'Sérums',
    price: 230.00,
    image: 'images/Glow-Deep-Serum.png',
    stock: 15,
    skinType: 'Grasa',
  },
  {
    id: '16',
    name: 'Centella Unscented Serum',
    brand: 'Purito',
    category: 'Sérums',
    price: 235.00,
    image: 'images/centella-Unscented-Serum.png',
    stock: 10,
    skinType: 'Sensible',
  },
  {
    id: '17',
    name: 'Madagascar Centella Ampoule',
    brand: 'Skin1004',
    category: 'Sérums',
    price: 255.00,
    image: 'images/Madagascar-Centella-Ampoule.png',
    stock: 14,
    skinType: 'Grasa',
  },
  {
    id: '18',
    name: 'Full Fit Propolis Serum',
    brand: 'COSRX',
    category: 'Sérums',
    price: 240.00,
    image: 'images/Full-Fit-Propolis-Serum.png',
    stock: 9,
    skinType: 'Mixta',
  },

  // HIDRATANTES
  {
    id: '19',
    name: 'Balancium Comfort Ceramide Cream',
    brand: 'COSRX',
    category: 'Hidratantes',
    price: 240.00,
    image: 'images/Balancium-Comfort-Ceramide-Cream.png',
    stock: 14,
    skinType: 'Seca',
  },
  {
    id: '20',
    name: 'Bean Cream',
    brand: 'Mixsoon',
    category: 'Hidratantes',
    price: 250.00,
    image: 'images/Bean-Cream.png',
    stock: 9,
    skinType: 'Seca',
  },
  {
    id: '21',
    name: 'Dynasty Cream',
    brand: 'Beauty of Joseon',
    category: 'Hidratantes',
    price: 245.00,
    image: 'images/Dynasty-Cream.png',
    stock: 12,
    skinType: 'Mixta',
  },
  {
    id: '22',
    name: 'B5 Panthenol Re-barrier Cream',
    brand: 'Purito',
    category: 'Hidratantes',
    price: 235.00,
    image: 'images/B5-Panthenol-Re-barrier-Cream.png',
    stock: 16,
    skinType: 'Sensible',
  },
  {
    id: '23',
    name: 'Hyalu-Cica Moisture Cream',
    brand: 'Skin1004',
    category: 'Hidratantes',
    price: 255.00,
    image: 'images/Hyalu-Cica-Moisture-Cream.png',
    stock: 13,
    skinType: 'Seca',
  },
  {
    id: '24',
    name: 'Oil-Free Ultra Moisturizing Lotion',
    brand: 'COSRX',
    category: 'Hidratantes',
    price: 220.00,
    image: 'images/Oil-Free-Ultra-Moisturizing-Lotion.png',
    stock: 18,
    skinType: 'Grasa',
  },

  // PROTECCIÓN SOLAR
  {
    id: '25',
    name: 'Relief Sun Rice + Probiotics',
    brand: 'Beauty of Joseon',
    category: 'Protección Solar',
    price: 190.00,
    image: 'images/Relief-Sun-Rice-Probiotics.png',
    stock: 22,
    skinType: 'Mixta',
  },
  {
    id: '26',
    name: 'Daily Soft Touch Sunscreen',
    brand: 'Purito',
    category: 'Protección Solar',
    price: 210.00,
    image: 'images/Daily-Soft-Touch-Sunscreen.png',
    stock: 18,
    skinType: 'Sensible',
  },
  {
    id: '27',
    name: 'Hyalu-Cica Water-Fit Sun Serum',
    brand: 'Skin1004',
    category: 'Protección Solar',
    price: 240.00,
    image: 'images/Hyalu-Cica-Water-Fit-Sun-Serum.png',
    stock: 16,
    skinType: 'Seca',
  },
  {
    id: '28',
    name: 'Aloe Soothing Sun Cream',
    brand: 'COSRX',
    category: 'Protección Solar',
    price: 200.00,
    image: 'images/Aloe-Soothing-Sun-Cream.png',
    stock: 20,
    skinType: 'Grasa',
  },
  {
    id: '29',
    name: 'Cica Sun Essence',
    brand: 'Mixsoon',
    category: 'Protección Solar',
    price: 225.00,
    image: 'images/Cica-Sun-Essence.png',
    stock: 11,
    skinType: 'Mixta',
  },
  {
    id: '30',
    name: 'Matte Sun Stick Mugwort',
    brand: 'Beauty of Joseon',
    category: 'Protección Solar',
    price: 215.00,
    image: 'images/Matte-Sun-Stick-Mugwort.png',
    stock: 15,
    skinType: 'Grasa',
  },
  // MASCARILLAS
{
  id: '31',
  name: 'Ultimate Nourishing Rice Mask',
  brand: 'COSRX',
  category: 'Mascarillas',
  price: 195.00,
  image: 'images/Ultimate-Nourishing-Rice-Mask.png',
  stock: 10,
  skinType: 'Seca',
},
{
  id: '32',
  name: 'Bifida Mask Pack',
  brand: 'Mixsoon',
  category: 'Mascarillas',
  price: 120.00,
  image: 'images/Bifida-Mask-Pack.png',
  stock: 25,
  skinType: 'Mixta',
},
{
  id: '33',
  name: 'Red Bean Refreshing Pore Mask',
  brand: 'Beauty of Joseon',
  category: 'Mascarillas',
  price: 205.00,
  image: 'images/Red-Bean-Refreshing-Pore-Mask.png',
  stock: 8,
  skinType: 'Grasa',
},
{
  id: '34',
  name: 'Dermide Cica Barrier Sleeping Pack',
  brand: 'Purito',
  category: 'Mascarillas',
  price: 215.00,
  image: 'images/Dermide-Cica-Barrier-Sleeping-Pack.png',
  stock: 14,
  skinType: 'Sensible',
},
{
  id: '35',
  name: 'Madagascar Centella Quick Calming Pad',
  brand: 'Skin1004',
  category: 'Mascarillas',
  price: 230.00,
  image: 'images/Madagascar-Centella-Quick-Calming-Pad.png',
  stock: 12,
  skinType: 'Mixta',
},
{
  id: '36',
  name: 'Honey Overnight Mask',
  brand: 'COSRX',
  category: 'Mascarillas',
  price: 185.00,
  image: 'images/Honey-Overnight-Mask.png',
  stock: 16,
  skinType: 'Seca',
},

// TRATAMIENTOS
{
  id: '37',
  name: 'AC Collection Spot Treatment',
  brand: 'COSRX',
  category: 'Tratamientos',
  price: 220.00,
  image: 'images/AC-Collection-Spot-Treatment.png',
  stock: 13,
  skinType: 'Grasa',
},
{
  id: '38',
  name: 'Centella Trouble Spot Gel',
  brand: 'Mixsoon',
  category: 'Tratamientos',
  price: 210.00,
  image: 'images/Centella-Trouble-Spot-Gel.png',
  stock: 11,
  skinType: 'Sensible',
},
{
  id: '39',
  name: 'Revive Eye Serum Ginseng + Retinal',
  brand: 'Beauty of Joseon',
  category: 'Tratamientos',
  price: 240.00,
  image: 'images/Revive-Eye-Serum-Ginseng-Retinal.png',
  stock: 9,
  skinType: 'Seca',
},
{
  id: '40',
  name: 'Centella Unscented Recovery Cream',
  brand: 'Purito',
  category: 'Tratamientos',
  price: 235.00,
  image: 'images/Centella-Unscented-Recovery-Cream.png',
  stock: 15,
  skinType: 'Sensible',
},
{
  id: '41',
  name: 'Tea-Trica Spot Cream',
  brand: 'Skin1004',
  category: 'Tratamientos',
  price: 225.00,
  image: 'images/Tea-Trica-Spot-Cream.png',
  stock: 12,
  skinType: 'Grasa',
},
{
  id: '42',
  name: 'Advanced Snail Peptide Eye Cream',
  brand: 'COSRX',
  category: 'Tratamientos',
  price: 250.00,
  image: 'images/Advanced-Snail-Peptide-Eye-Cream.png',
  stock: 10,
  skinType: 'Mixta',
},
]